version: '3.8'

services:
  ssl-analyzer:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=web/app.py
    command: gunicorn --bind 0.0.0.0:5000 --workers 4 --timeout 60 web.app:app
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  ssl-analyzer-dev:
    build: .
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - FLASK_APP=web/app.py
    command: python web/app.py
    volumes:
      - .:/app
      - ./logs:/app/logs
    profiles:
      - dev

volumes:
  logs:
    driver: local